In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("data/candidate_job_market_dataset1.csv")
df.shape

(120000, 31)

In [5]:
df.head()

,candidate_id,job_id,candidate_skills,education,years_experience,candidate_location,candidate_preferred_work_mode,job_title,required_skills,required_experience,...,student_internships,student_github_repos,student_hackathons_participated,student_coding_platform_rating,student_weekly_study_hours,student_career_label,student_experience_level,student_interests,fit_label,expected_salary_lpa
0,C000001,J000001,"SQL, Pandas, NumPy",MCA,0,Gurugram,On-site,Machine Learning Intern,"Python, Machine Learning, Pandas, NumPy, Sciki...",1,...,1.0,6.0,0.0,NaN,5.3,Software Engineer,Beginner,System Design,1,8.96
1,C000002,J000002,"Data Analysis, Tableau, Statistics, Excel, Pyt...",B.Tech,3,Mumbai,Hybrid,Data Analyst Intern,"Python, SQL, Excel, Power BI, Tableau, Data An...",1,...,1.0,2.0,1.0,NaN,12.0,ML Engineer,Intermediate,"Artificial Intelligence, Machine Learning",1,10.30
2,C000003,J000003,"Python, SQL, Data Analysis, Azure, JavaScript",B.Tech,4,Hyderabad,On-site,Python Developer Intern,"Python, Django, Flask, FastAPI, SQL, Git",1,...,0.0,3.0,2.0,1325.0,15.9,Data Scientist,Beginner,Statistics,0,11.35
3,C000004,J000004,"Python, SQL, Statistics, Excel, Tableau, JavaS...",M.Tech,1,Mumbai,Hybrid,Data Analyst Intern,"Python, SQL, Excel, Power BI, Tableau, Data An...",0,...,1.0,11.0,2.0,1893.0,5.9,Backend Developer,Intermediate,"Databases, Software Engineering",1,8.77
4,C000005,J000005,"Machine Learning, PyTorch, TensorFlow, NLP",B.Tech,0,Hyderabad,Remote,AI Intern,"Python, Machine Learning, Deep Learning, NLP, ...",0,...,1.0,7.0,2.0,NaN,10.5,ML Engineer,Intermediate,"Automation, Artificial Intelligence",1,8.16

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 31 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   candidate_id                     120000 non-null  str
 1   job_id                           120000 non-null  str
 2   candidate_skills                 120000 non-null  str
 3   education                        120000 non-null  str
 4   years_experience                 120000 non-null  int64
 5   candidate_location               120000 non-null  str
 6   candidate_preferred_work_mode    120000 non-null  str
 7   job_title                        120000 non-null  str
 8   required_skills                  120000 non-null  str
 9   required_experience              120000 non-null  int64
 10  job_location                     120000 non-null  str
 11  work_mode                        120000 non-null  str
 12  company_size                     120000 non-null  str
 13  industry                         120000 non-null  str
 14  job_duration_months              120000 non-null  int64
 15  skill_overlap                    120000 non-null  int64
 16  skill_coverage                   120000 non-null  float64
 17  student_year_of_study            120000 non-null  int64
 18  student_cgpa                     107673 non-null  float64
 19  student_num_projects             114281 non-null  float64
 20  student_certifications           84433 non-null   str
 21  student_internships              113008 non-null  float64
 22  student_github_repos             106662 non-null  float64
 23  student_hackathons_participated  111793 non-null  float64
 24  student_coding_platform_rating   92976 non-null   float64
 25  student_weekly_study_hours       108933 non-null  float64
 26  student_career_label             118382 non-null  str
 27  student_experience_level         116310 non-null  str
 28  student_interests                111777 non-null  str
 29  fit_label                        120000 non-null  int64
 30  expected_salary_lpa              120000 non-null  float64
dtypes: float64(9), int64(6), str(16)
memory usage: 57.3 MB

In [7]:
df.isnull().sum()

candidate_id                           0
job_id                                 0
candidate_skills                       0
education                              0
years_experience                       0
candidate_location                     0
candidate_preferred_work_mode          0
job_title                              0
required_skills                        0
required_experience                    0
job_location                           0
work_mode                              0
company_size                           0
industry                               0
job_duration_months                    0
skill_overlap                          0
skill_coverage                         0
student_year_of_study                  0
student_cgpa                       12327
student_num_projects                5719
student_certifications             35567
student_internships                 6992
student_github_repos               13338
student_hackathons_participated     8207
student_coding_platform_rating     27024
student_weekly_study_hours         11067
student_career_label                1618
student_experience_level            3690
student_interests                   8223
fit_label                              0
expected_salary_lpa                    0
dtype: int64

In [8]:
df.isnull().sum().sort_values(ascending=False)

student_certifications             35567
student_coding_platform_rating     27024
student_github_repos               13338
student_cgpa                       12327
student_weekly_study_hours         11067
student_interests                   8223
student_hackathons_participated     8207
student_internships                 6992
student_num_projects                5719
student_experience_level            3690
student_career_label                1618
education                              0
candidate_id                           0
job_id                                 0
candidate_skills                       0
job_duration_months                    0
industry                               0
company_size                           0
work_mode                              0
job_location                           0
required_experience                    0
required_skills                        0
job_title                              0
candidate_preferred_work_mode          0
candidate_location                     0
years_experience                       0
student_year_of_study                  0
skill_coverage                         0
skill_overlap                          0
fit_label                              0
expected_salary_lpa                    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.nunique().sort_values()

fit_label                               2
candidate_preferred_work_mode           3
work_mode                               3
required_experience                     3
student_experience_level                3
student_year_of_study                   4
job_duration_months                     4
company_size                            5
student_internships                     5
education                               5
years_experience                        5
student_hackathons_participated         7
skill_overlap                           7
job_title                               8
industry                                8
required_skills                         8
student_num_projects                    9
candidate_location                     10
job_location                           10
student_career_label                   11
skill_coverage                         16
student_github_repos                   30
student_interests                     136
student_weekly_study_hours            201
student_cgpa                          399
student_certifications                575
student_coding_platform_rating        983
expected_salary_lpa                  1069
candidate_skills                    76437
job_id                             120000
candidate_id                       120000
dtype: int64

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
years_experience,120000.0,1.998192,1.413868,0.000,1.000,2.000,3.000,4.00
required_experience,120000.0,0.994675,0.816773,0.000,0.000,1.000,2.000,2.00
job_duration_months,120000.0,3.939425,1.463930,2.000,3.000,3.000,6.000,6.00
skill_overlap,120000.0,3.452450,1.555381,1.000,2.000,3.000,5.000,7.00
skill_coverage,120000.0,0.575251,0.253735,0.143,0.333,0.571,0.833,1.00
student_year_of_study,120000.0,2.619667,0.926420,1.000,2.000,3.000,3.000,4.00
student_cgpa,107673.0,7.703439,0.888063,5.000,7.100,7.700,8.300,9.90
student_num_projects,114281.0,2.702899,1.826710,0.000,1.000,2.000,4.000,8.00
student_internships,113008.0,0.653556,0.904657,0.000,0.000,0.000,1.000,4.00
student_github_repos,106662.0,8.444873,4.683460,0.000,5.000,8.000,11.000,31.00
student_hackathons_participated,111793.0,1.046711,1.108779,0.000,0.000,1.000,2.000,6.00
student_coding_platform_rating,92976.0,1710.054509,491.116731,809.000,1506.000,1691.000,1884.000,9999.00
student_weekly_study_hours,108933.0,10.448701,19.423821,-5.000,6.200,8.900,11.600,300.00
fit_label,120000.0,0.600000,0.489900,0.000,0.000,1.000,1.000,1.00
expected_salary_lpa,120000.0,9.850011,1.563478,4.110,8.780,9.850,10.920,16.57

### CATEGORICAL CONSISTENCY

In [18]:
cat_cols = df.select_dtypes(include='object').columns
cat_cols

C:\Users\vartika singh\AppData\Local\Temp\ipykernel_27144\910776789.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

Index(['candidate_id', 'job_id', 'candidate_skills', 'education',
       'candidate_location', 'candidate_preferred_work_mode', 'job_title',
       'required_skills', 'job_location', 'work_mode', 'company_size',
       'industry', 'student_certifications', 'student_career_label',
       'student_experience_level', 'student_interests'],
      dtype='str')

In [19]:
for col in cat_cols:
    print("\nColumn:", col)
    print("Unique values:", df[col].nunique())
    print(df[col].value_counts(dropna=False).head(15))

Column: candidate_id
Unique values: 120000
candidate_id
C000001    1
C000002    1
C000003    1
C000004    1
C000005    1
C000006    1
C000007    1
C000008    1
C000009    1
C000010    1
C000011    1
C000012    1
C000013    1
C000014    1
C000015    1
Name: count, dtype: int64

Column: job_id
Unique values: 120000
job_id
J000001    1
J000002    1
J000003    1
J000004    1
J000005    1
J000006    1
J000007    1
J000008    1
J000009    1
J000010    1
J000011    1
J000012    1
J000013    1
J000014    1
J000015    1
Name: count, dtype: int64

Column: candidate_skills
Unique values: 76437
candidate_skills
Python              465
SQL                 403
Git                 326
Machine Learning    190
Docker              145
NumPy               140
Python, SQL         139
Pandas              139
HTML                137
Java                137
CSS                 133
SQL, Python         133
JavaScript          131
React               128
Flask               100
Name: count, dtype: int64

Column: education
Unique values: 5
education
B.Tech    24199
M.Tech    24088
BCA       23984
MCA       23899
B.Sc      23830
Name: count, dtype: int64

Column: candidate_location
Unique values: 10
candidate_location
Chennai      12209
Pune         12127
Bangalore    12065
Delhi        12046
Remote       12029
Mumbai       11986
Gurugram     11930
Noida        11920
Hyderabad    11845
Ghaziabad    11843
Name: count, dtype: int64

Column: candidate_preferred_work_mode
Unique values: 3
candidate_preferred_work_mode
Remote     47780
Hybrid     42202
On-site    30018
Name: count, dtype: int64

Column: job_title
Unique values: 8
job_title
AI Intern                    15213
Python Developer Intern      15126
Machine Learning Intern      15077
Data Analyst Intern          14996
Backend Developer Intern     14990
Frontend Developer Intern    14957
Data Science Intern          14864
Software Engineer Intern     14777
Name: count, dtype: int64

Column: required_skills
Unique values: 8
required_skills
Python, Machine Learning, Deep Learning, NLP, PyTorch, TensorFlow    15213
Python, Django, Flask, FastAPI, SQL, Git                             15126
Python, Machine Learning, Pandas, NumPy, Scikit-learn, SQL           15077
Python, SQL, Excel, Power BI, Tableau, Data Analysis, Statistics     14996
Python, Java, Node.js, SQL, Git, Docker                              14990
HTML, CSS, JavaScript, React, Git                                    14957
Python, SQL, Pandas, NumPy, Machine Learning, Statistics             14864
Python, Java, C++, SQL, Git, Docker                                  14777
Name: count, dtype: int64

Column: job_location
Unique values: 10
job_location
Delhi        12138
Chennai      12129
Remote       12103
Pune         12095
Bangalore    12086
Noida        11989
Ghaziabad    11912
Mumbai       11897
Hyderabad    11871
Gurugram     11780
Name: count, dtype: int64

Column: work_mode
Unique values: 3
work_mode
Remote     40188
Hybrid     39976
On-site    39836
Name: count, dtype: int64

Column: company_size
Unique values: 5
company_size
Startup (1-50)         26509
Medium (201-1000)      26316
Small (51-200)         26316
Large (1001-10000)     23971
Enterprise (10000+)    16888
Name: count, dtype: int64

Column: industry
Unique values: 8
industry
IT Services             26624
Product / SaaS          24000
E-commerce              16805
FinTech                 15540
EdTech                  12012
HealthTech              10760
Consulting               8341
Manufacturing / Auto     5918
Name: count, dtype: int64

Column: student_certifications
Unique values: 575
student_certifications
NaN                             35567
Google Data Analytics            2891
Coursera ML Specialization       2463
TensorFlow Developer             1895
Oracle Java SE                   1851
Deep Learning Specialization     1734
HackerRank Problem Solving       1595
Excel Advanced                   1509
freeCodeCamp Responsive Web      1461
Coursera DSA                     1438
Google Cloud Associate           1429
Meta Front-End                   1377
Microsoft PL-300                 1364
AWS ML Specialty                 1358
IBM Data Science                 1280
Name: count, dtype: int64

Column: student_career_label
Unique values: 11
student_career_label
Data Scientist           18058
Data Analyst             15358
Software Engineer        14611
Backend Developer        12638
ML Engineer              12270
Cloud/DevOps Engineer    11674
AI Engineer              10672
Cybersecurity Analyst     8594
Web Developer             8417
Frontend Developer        3172
Full Stack Developer      2918
NaN                       1618
Name: count, dtype: int64

Column: student_experience_level
Unique values: 3
student_experience_level
Beginner        62227
Intermediate    38943
Advanced        15140
NaN              3690
Name: count, dtype: int64

Column: student_interests
Unique values: 136
student_interests
NaN                                    8223
Artificial Intelligence                3500
Analytics                              2857
System Design                          2375
Automation                             1913
Software Engineering                   1887
System Design, Software Engineering    1513
Data Science                           1465
Statistics                             1374
UI, UX                                 1308
Data Visualization                     1255
Business Analytics                     1229
Business Analytics, Analytics          1213
MLOps                                  1168
Competitive Programming                1137
Name: count, dtype: int64

In [21]:
print("Candidate Skills:")
print(df['candidate_skills'].value_counts(dropna=False).head(15))

Candidate Skills:
candidate_skills
Python              465
SQL                 403
Git                 326
Machine Learning    190
Docker              145
NumPy               140
Python, SQL         139
Pandas              139
HTML                137
Java                137
CSS                 133
SQL, Python         133
JavaScript          131
React               128
Flask               100
Name: count, dtype: int64

In [22]:
df['candidate_skills'] = df['candidate_skills'].replace({
    'SQL, Python': 'Python, SQL'
})

In [23]:
df['candidate_skills'].value_counts().head(15)

candidate_skills
Python              465
SQL                 403
Git                 326
Python, SQL         272
Machine Learning    190
Docker              145
NumPy               140
Pandas              139
HTML                137
Java                137
CSS                 133
JavaScript          131
React               128
Flask               100
Statistics           97
Name: count, dtype: int64

In [24]:
print("Student Interests:")
print(df['student_interests'].value_counts(dropna=False).head(15))

Student Interests:
student_interests
NaN                                    8223
Artificial Intelligence                3500
Analytics                              2857
System Design                          2375
Automation                             1913
Software Engineering                   1887
System Design, Software Engineering    1513
Data Science                           1465
Statistics                             1374
UI, UX                                 1308
Data Visualization                     1255
Business Analytics                     1229
Business Analytics, Analytics          1213
MLOps                                  1168
Competitive Programming                1137
Name: count, dtype: int64

In [25]:
df['student_interests'] = df['student_interests'].replace({
    'Business Analytics, Analytics': 'Business Analytics'
})

In [26]:
df['student_interests'].value_counts().head(15)

student_interests
Artificial Intelligence                3500
Analytics                              2857
Business Analytics                     2442
System Design                          2375
Automation                             1913
Software Engineering                   1887
System Design, Software Engineering    1513
Data Science                           1465
Statistics                             1374
UI, UX                                 1308
Data Visualization                     1255
MLOps                                  1168
Competitive Programming                1137
Statistics, Data Science               1128
Startups                               1112
Name: count, dtype: int64

### LOGICAL &REFERENTIAL CHECKS

In [27]:
df[['years_experience', 'required_experience']].describe()

       years_experience  required_experience
count     120000.000000        120000.000000
mean           1.998192             0.994675
std            1.413868             0.816773
min            0.000000             0.000000
25%            1.000000             0.000000
50%            2.000000             1.000000
75%            3.000000             2.000000
max            4.000000             2.000000

In [28]:
(df['years_experience'] < df['required_experience']).sum()

np.int64(23756)

In [32]:
(df['years_experience'] < 0).sum()

np.int64(0)

In [33]:
(df['years_experience'] < 0).sum()

np.int64(0)

In [34]:
(df['required_experience'] < 0).sum()

np.int64(0)

In [35]:
(df['student_cgpa'] < 0).sum(), (df['student_cgpa'] > 10).sum()

(np.int64(0), np.int64(0))

In [36]:
(df['student_num_projects'] < 0).sum()

np.int64(0)

In [37]:
(df['student_internships'] < 0).sum()

np.int64(0)

In [38]:
(df['student_hackathons_participated'] < 0).sum()

np.int64(0)

In [39]:
(df['student_weekly_study_hours'] < 0).sum()

np.int64(347)

In [42]:
df.loc[df['student_weekly_study_hours'] < 0, 'student_weekly_study_hours'] = 0

In [43]:
(df['student_weekly_study_hours'] < 0).sum()

np.int64(0)

In [41]:
num_cols = df.select_dtypes(include='number').columns
num_cols

Index(['years_experience', 'required_experience', 'job_duration_months',
       'skill_overlap', 'skill_coverage', 'student_year_of_study',
       'student_cgpa', 'student_num_projects', 'student_internships',
       'student_github_repos', 'student_hackathons_participated',
       'student_coding_platform_rating', 'student_weekly_study_hours',
       'fit_label', 'expected_salary_lpa'],
      dtype='str')

In [44]:
sk = df[num_cols].skew().sort_values(ascending=False)
sk

student_weekly_study_hours         12.401421
student_coding_platform_rating     11.380122
student_internships                 1.477269
student_hackathons_participated     1.088721
student_github_repos                0.772019
student_num_projects                0.632408
job_duration_months                 0.383073
skill_overlap                       0.095275
skill_coverage                      0.013784
expected_salary_lpa                 0.013045
required_experience                 0.009786
student_cgpa                        0.007810
years_experience                   -0.000182
student_year_of_study              -0.064217
fit_label                          -0.408253
dtype: float64

In [45]:
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1
count = ((df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR))).sum()

count.sort_values(ascending=False)

student_internships                5392
student_github_repos               1597
student_weekly_study_hours         1158
expected_salary_lpa                 626
student_coding_platform_rating      534
student_cgpa                        239
student_hackathons_participated     220
student_year_of_study                 0
skill_coverage                        0
skill_overlap                         0
job_duration_months                   0
years_experience                      0
required_experience                   0
student_num_projects                  0
fit_label                             0
dtype: int64